export const fighters = [
   {
      name: 'Annoyed Karen',
      imgSrc: 'Karen.png',
      health: 67,
      attack: '14 - 18',
      special: 'Passive Aggressiveness',
      weakness: 'Logical thinking',
   },
   {
      name: 'Mad Suzie',
      imgSrc: 'MadSuzie.png',
      health: 78,
      attack: '12 - 18',
      special: 'Fist Punch',
      weakness: 'Pink color',
   },
   {
      name: 'Jenny Wick',
      imgSrc: 'JennyWick.png',
      health: 55,
      attack: '22 - 24',
      special: 'Pencil Stab',
      weakness: 'Contrast',
   },
   {
      name: 'Purple Pie',
      imgSrc: 'PurplePie.png',
      health: 80,
      attack: '9 - 12',
      special: 'Roasting',
      weakness: 'Sunscreen',
   },
   {
      name: 'Pale Lora',
      imgSrc: 'PaleLora.png',
      health: 60,
      attack: '15 - 16',
      special: 'Bleach Splash',
      weakness: 'Candy Cotton',
   },
   {
      name: 'Ivy Irene',
      imgSrc: 'IvyIrene.png',
      health: 70,
      attack: '10 - 14',
      special: 'Potion Pill',
      weakness: 'Broccoli',
   },
];
